baseURL = 'https://www.momentumbusiness.org/'
languageCode = 'en-us'
title = 'Momentum Business Solutions'

[params]
  description = 'Expert bookkeeping, payroll processing, and financial consulting for growing businesses. QuickBooks ProAdvisor certified. Serving businesses with $500K-$5M revenue.'
  email = 'cade@momentumbusiness.org'
  phone = '(509) 554-8022'
  founder = 'Cade Maldonado'
  founderTitle = 'Founder & CEO'
  founderLinkedIn = 'https://www.linkedin.com/in/cade-maldonado-a71801104'
  companyLinkedIn = 'https://www.linkedin.com/company/momentum-business-solutions-llc'

  [params.address]
    locality = 'Richland'
    region = 'WA'
    country = 'US'
    lat = '46.2857'
    lng = '-119.2844'

  [params.ogImage]
    url = 'https://momentumbusiness.org/og-image.jpg'
    width = 1200
    height = 630

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
